### ISSUE TITLE
Needs linting

### ISSUE THREAD

**Issue by seankross** [getwilds/cancerprof#52]
See: https://lintr.r-lib.org/

- Clean up the package via iterative lints: `lintr::lint_package()`
- Set up linting via gh actions: `usethis::use_github_action("lint")`

Also @sckott may have tips. (I have only gotten serious about lintr since Scott joined DaSL)

**Comment by sckott** [comment]
I think we're still undecided as to whether to have a certain style we'll want all R pkgs to follow, so for now the default that's used I think is the tidyverse style https://styler.r-lib.org/reference/tidyverse_style.html which i think is pretty good

we have some tips in the guide https://getwilds.org/guide/style.html#r

i think it's good to meet people where they are, that is, one person may use Rstudio, whereas another uses Vs code, and another uses something else - and tied to how you use R are different ways to run stylers/inters - so pick what's comfortable for you - but in addition use the github action, so if you forget to style locally you'll get a reminder from the bots
