### ISSUE TITLE
pkgdown site?

### ISSUE THREAD

**Issue by sckott** [getwilds/cancerprof#58]
If there will be one https://pkgdown.r-lib.org/ ...

- consider using `@family` to group related fxns so users can find them easier, e.g., all the `handle_` fxns 
- ...

**Comment by realbp** [comment]
Yup, the package down site is created, im not sure if it is ready to be published but it is on my local storage. I am not sure what you mean by @family, I was not able to find it in the package down documentations. 
All of the handle functions will not be exported so it wont show in pkgdown, but I will make sure to group similar functions!

**Comment by sckott** [comment]
read up here for https://roxygen2.r-lib.org/articles/index-crossref.html#family family stuff
