### ISSUE TITLE
Order of parameters

### ISSUE THREAD

**Issue by sckott** [getwilds/cancerprof#59]
Typically  - at least what I'm familiar with - required parameters go first, with optional parameters (including those with default values) last. 

e.g., in `demo_crowding` you have

```r
function(area, areatype, 
                          crowding = "household with >1 person per room", 
                          race)
```

whereas i'd want `crowding` to go last

```r
function(area, areatype, race,
                          crowding = "household with >1 person per room")
                          
```

do other folks have other ideas?

**Comment by howardbaek** [comment]
100% agreed.
