### ISSUE TITLE
Handling http errors

### ISSUE THREAD

**Issue by sckott** [getwilds/cancerprof#61]
I don't see any explicit HTTP error handling in the package, but maybe it's not needed. I just dn't know enough about the website to know if it's needed. Do you ever end up with 400 or above series HTTP status codes? If so, should handle that kind of result in probably here https://github.com/getwilds/cancerprof/blob/main/R/process-response.R

**Comment by sckott** [comment]
though I think maybe `httr2` errors already if you get a 400 or above error?

**Comment by realbp** [comment]
@sckott according to the httr2 docs, "Responses with status codes 4xx and 5xx are HTTP errors. httr2 automatically turns these into R errors"
https://httr2.r-lib.org/articles/httr2.html
So my guess is that error handling is not needed. Please let me know if you think otherwise!

**Comment by sckott** [comment]
Okay. If you can find a http request that does throw a 400 or 500 error from the website, it'd be good to check if that is in fact the case. 

It's possible that the http status codes are not returned correctly from the website, so these automatic errors may not happen. That is, the website devs may not appropriately set the HTTP status codes so a real error may not be reflected in the status codes, which is what httr2 needs to do the automatic erroring on the R side.

**Comment by realbp** [comment]
I was not able to find any requests that thorw a 400 or 500 error, so I think you are correct that state cancer profiles does not correctly set the HTTP codes. I have added some error handling after performoing the httr2 request to make sure that users are inputting the correct arguments. 

```
if (httr2::resp_content_type(resp) != "text/csv") {
    cli_abort("Invalid input, please check documentation for valid arguments.")
}
```
  
 Sean and I figured out that even SCP will throw a 200 status even if the uesr gives an incorrect api request, BUT the content type of a correct request is different from an incorrect request.

**Comment by sckott** [comment]
> throw a 200 status even if the uesr gives an incorrect api request, BUT the content type of a correct request is different from an incorrect request.

Classic problem in scraping websites! That's great the content type is different in that you have some signal that something is wrong. It's hard for me to say how to proceed to do good error handling - BUT it seems like you're doing a lot of work to prevent users from doing requests in your package that will lead to bad requests, so it's probably not too important to handle errors from the website. 

If either of you have any contacts there you could message them and bring up the issue of improper use of http status codes

**Comment by realbp** [comment]
Great! Thank you for you feedback Scott!
